### ISSUE TITLE
Scripts and checkpoints for Vision tasks

### ISSUE THREAD

**Issue by AsawareeBhide** [OFA-Sys/ONE-PEACE#11]
Hi, super interesting work!
When will training scripts, datasets and finetuned checkpoints for Vision tasks be released?

**Comment by simonJJJ** [comment]
Hi @AsawareeBhide, training scripts and checkpoints for vision tasks are available at [here](https://github.com/OFA-Sys/ONE-PEACE/tree/main/one_peace_vision).
