### ISSUE TITLE
Excuse me, how can i debug it on single gpu or multi gpu on vscode or others?

### ISSUE THREAD

**Issue by Kukty** [OFA-Sys/ONE-PEACE#12]
Hello, i am a beginner and want to learn how the model is build and trained, but i can't debug it on vscode by single or multi gups, can you help me?

**Comment by logicwong** [comment]
You can debug with `one_peace/train.py` or `one_peace/evaluate.py`. Remember to fill in the parameters. Below is an Pycharm example

![image](https://github.com/OFA-Sys/ONE-PEACE/assets/36780733/1d8f0bac-8b02-4f17-ba48-1d4c1f445239)
