### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by diablofanfanfan** [OFA-Sys/ONE-PEACE#16]
Why are there errors in the files I download?  like（from fairseq.models.transformer import EncDecBaseConfig）.

Errors such as “ImportError: cannot import name 'EncDecBaseConfig' from 'fairseq.models.transformer' (C:\pk\.conda\envs\py37\lib\site-packages\fairseq\models\transformer\__init__.py)” may occur during operation.

**Comment by logicwong** [comment]
@diablofanfanfan Can you provide more details? You can first try `pip uninstall fairseq`, and then reinstall the dependencies based on the instructions provided in the [readme](https://github.com/OFA-Sys/ONE-PEACE#requirements-and-installation).

**Comment by diablofanfanfan** [comment]
Thank you for your help. I tried, but there was still a problem with “cannot import name 'EncDecBaseConfig' from 'fairseq.models.transformer'”.

In file ONE-PEACE-main\one_peace\models\unify_model_config.py. "from fairseq.models.transformer import EncDecBaseConfig" will result in an error.

**Comment by logicwong** [comment]
It seems there is an issue with the Fairseq installation. Can you please provide the installation log so we can troubleshoot the problem?

**Comment by diablofanfanfan** [comment]
[console_scripts]
fairseq-eval-lm = fairseq_cli.eval_lm:cli_main
fairseq-generate = fairseq_cli.generate:cli_main
fairseq-hydra-train = fairseq_cli.hydra_train:cli_main
fairseq-interactive = fairseq_cli.interactive:cli_main
fairseq-preprocess = fairseq_cli.preprocess:cli_main
fairseq-score = fairseq_cli.score:cli_main
fairseq-train = fairseq_cli.train:cli_main
fairseq-validate = fairseq_cli.validate:cli_main

**Comment by diablofanfanfan** [comment]
What environments do I need to install if I want to run in windows?

**Comment by logicwong** [comment]
@diablofanfanfan We haven't tried running ONE-PEACE in Windows. We strongly recommend running this project on Linux, which will avoid some environment dependency issues. If you still want to run it in Windows, you may need to search for a solution in [Fairseq](https://github.com/facebookresearch/fairseq).
