### ISSUE TITLE
GPU Device Config

### ISSUE THREAD

**Issue by 3xWangDot** [OFA-Sys/ONE-PEACE#20]
Thanks for sharing this project and codebase.
May I know the GPU device config you used in the pre-trained Stage1/2 ? (e.g. what type of GPU and how many of them)
I didn't find it in the paper and project page.
Thanks.

**Comment by logicwong** [comment]
@3xWangDot We trained ONE-PEACE on 256 A100 GPU with 80GB of RAM (256 for Stage1 and 32 for Stage2). The training process took approximately 20 days.
