### ISSUE TITLE
Request and Update for Inference Script/Colab Notebook

### ISSUE THREAD

**Issue by hanoonaR** [OFA-Sys/ONE-PEACE#21]
Dear Authors,

Thank you for sharing your great work. Could you please provide an inference script or Colab notebook for visual grounding tasks? As per @logicwong comment on [issue #19](https://github.com/OFA-Sys/ONE-PEACE/issues/19#issuecomment-1635837876), it was indicated that a release was planned this week. I was hoping you could kindly provide an update on this. 

Thank you for your time and efforts.

**Comment by logicwong** [comment]
@hanoonaR We have provided the [visual grounding API](https://github.com/OFA-Sys/ONE-PEACE#visual-grounding) in our repo, hope it can help you.
