### ISSUE TITLE
About the device requirement on the segmentation task

### ISSUE THREAD

**Issue by SaulZhang** [OFA-Sys/ONE-PEACE#22]
I encountered an out-of-memory error on an 8*RTX 3080 (11G) workstation during fine-tuning of segmentation tasks on the ADE20K Dataset. I would like to know the required GPU memory for this task. Thanks!

**Comment by simonJJJ** [comment]
Hi @SaulZhang, thanks for your interest. We use 80G memory GPUs for fine-tuning on 896x896 resolution. I suggest using lower input resolutions like 512x512.
