### ISSUE TITLE
About the pre-trained model loading

### ISSUE THREAD

**Issue by SaulZhang** [OFA-Sys/ONE-PEACE#23]
Hello @simonJJJ, while attempting to fine-tune the segmentation task using the pre-trained model `one-peace-vision.pkl`, I encountered an error as follows:
> Traceback (most recent call last):
>   File "train.py", line 243, in <module>
>     main()
>   File "train.py", line 232, in main
>     train_segmentor(
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmseg/apis/train.py", line 193, in train_segmentor
>     runner.load_checkpoint(cfg.load_from)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 339, in load_checkpoint
>     return load_checkpoint(
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 581, in load_checkpoint
>     checkpoint = _load_checkpoint(filename, map_location, logger)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 520, in _load_checkpoint
>     return CheckpointLoader.load_checkpoint(filename, map_location, logger)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 285, in load_checkpoint
>     return checkpoint_loader(filename, map_location)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 302, in load_from_local
>     checkpoint = torch.load(filename, map_location=map_location)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/torch/serialization.py", line 922, in _legacy_load
>     raise RuntimeError("Invalid magic number; corrupt file?")
> RuntimeError: Invalid magic number; corrupt file?

**Comment by simonJJJ** [comment]
Hi @SaulZhang.
When directly fine-tune on one-peace-vision.pkl, you should use --cfg-options model.pretrained=${CHECKPOINT_PATH} and do not use --load-from=${LOAD_FROM_PATH}.

**Comment by SaulZhang** [comment]
@simonJJJ Thanks! It works.
But when I finetune the one-peace-vison model in `384x384` resolution, another problem occurs. It seems that the reason is the different resolution with original setting `896x896`. How should i fix it?

>   main()
>   File "train.py", line 232, in main
>     train_segmentor(
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmseg/apis/train.py", line 194, in train_segmentor
>     runner.run(data_loaders, cfg.workflow)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 134, in run
>     iter_runner(iter_loaders[i], **kwargs)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 61, in train
>     outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/parallel/distributed.py", line 59, in train_step
>     output = self.module.train_step(*inputs[0], **kwargs[0])
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmseg/models/segmentors/base.py", line 138, in train_step
>     losses = self(**data_batch)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 110, in new_func
>     return old_func(*args, **kwargs)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/mmseg/models/segmentors/base.py", line 108, in forward
>     return self.forward_train(img, img_metas, **kwargs)
>   File "/data6/ONE-PEACE-main/one_peace_vision/seg/mmseg_custom/models/segmentors/encoder_decoder_mask2former.py", line 140, in forward_train
>     x = self.extract_feat(img)
>   File "/data6/ONE-PEACE-main/one_peace_vision/seg/mmseg_custom/models/segmentors/encoder_decoder_mask2former.py", line 66, in extract_feat
>     x = self.backbone(img)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data6/ONE-PEACE-main/one_peace_vision/seg/mmseg_custom/models/backbones/onepeace_adapter.py", line 101, in forward
>     x, self_attn_bias, H, W = self.image_adapter(x)
>   File "/data6/anaconda3/envs/mmseg-1.x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
> Traceback (most recent call last):
>   File "train.py", line 243, in <module>
>     return forward_call(*input, **kwargs)
>   File "/data6/ONE-PEACE-main/one_peace_vision/seg/mmseg_custom/models/backbones/onepeace.py", line 180, in forward
>     x += pos_embed.unsqueeze(0)
> RuntimeError: The size of tensor a (577) must match the size of tensor b (3137) at non-singleton dimension 1

**Comment by simonJJJ** [comment]
@SaulZhang You should change the crop_size to (384x384) and the model.backbone.bucket_size to 24 in the config file.
Also, you should change the img_scale in train_pipeline and test_pipeline in the config file according to the size ratio (384/896).
Another change you may need is the model.test_cfg.stride.
