### ISSUE TITLE
Problem of 'tsv' file

### ISSUE THREAD

**Issue by hanguniverse** [OFA-Sys/ONE-PEACE#25]
Thanks for your interesting work! I have a question when I want to evaluate the model (e.g , flickr),
should I first translate the dataset or caption into the type of 'tsv'？

**Comment by logicwong** [comment]
@hanguniverse 
If you want to evaluate **vision-language** or **audio** tasks, then you should indeed prepare the dataset in the 'tsv' format.
If you want to evaluate **vision** tasks like instance segmentation, you can prepare the data according to this [Readme](https://github.com/OFA-Sys/ONE-PEACE/tree/main/one_peace_vision).

**Comment by hanguniverse** [comment]
> 
@logicwong thanks for your quickly reply! By the way,  for answer1, should I translate both image and annoations to 'tsv' or just annotations? thank you !

**Comment by logicwong** [comment]
@hanguniverse You can follow this dataset [Flickr30k](http://one-peace-shanghai.oss-accelerate.aliyuncs.com/one_peace_datasets/flickr30k.zip) to prepare your data. It contains 3 columns, `image_id,image,caption`. `image` represents the path of the image, `caption` represents the annotation.

**Comment by hanguniverse** [comment]
@logicwong sorry to bother you again, the attached hyperlink of 'Flickr30k' cannot be opened, do you mean to download this dataset from its homepage?

**Comment by logicwong** [comment]
@hanguniverse Sorry, there seems to be something wrong with this link. try to use the following link:
https://one-peace-shanghai.oss-cn-shanghai.aliyuncs.com/one_peace_datasets/flickr30k.zip

**Comment by hanguniverse** [comment]
@logicwong ok, I will try it, thanks for your kind reply and look foward to your next work!

**Comment by hanguniverse** [comment]
@logicwong sorry， I downloaded the data,  but couldn't extract it, indicating that the file is corrupt，
I have try it twice.

**Comment by logicwong** [comment]
@hanguniverse Emmm, I downloaded and extracted it again, and there was no problem... Can you try using this link? https://one-peace-shanghai.oss-accelerate.aliyuncs.com/one_peace_datasets/flickr30k.zip

**Comment by hanguniverse** [comment]
@logicwong thanks! I have download the datatset succesfully, and I have another question that what is the differences between val and val_new?

**Comment by logicwong** [comment]
val is the full validation set, each image contains 5 captions. val_new is the selected val set, each image only contains 1 caption.

**Comment by hanguniverse** [comment]
I see, thanks for your pacient reply
