### ISSUE TITLE
is it possible to export to Onnx model

### ISSUE THREAD

**Issue by eisneim** [OFA-Sys/ONE-PEACE#28]
this is a very useful project, would be great if it can be used in production with onnx support

**Comment by logicwong** [comment]
I'm new to onnx, so I'm wondering if you could submit a pull request?

**Comment by eisneim** [comment]
that would be hard for me😢

**Comment by logicwong** [comment]
Maybe we can wait for some kind guys to help us...

**Comment by jacksteussie** [comment]
@eisneim  I don't know if you just want the vision branch, but if you do, I know  mmsegmentation and mmdetection, the frameworks used for the downstream segmentation and detection tasks, each have a script that can be used to convert a model to onnx format, although I haven't tested it so I do not know for sure if it works.

**Comment by eisneim** [comment]
@jacksteussie thanks
