### ISSUE TITLE
Visual Grounding

### ISSUE THREAD

**Issue by RYHSmmc** [OFA-Sys/ONE-PEACE#30]
One-Peace, such nice work. I want to funtune a Visual Grounding model use custom dataset, can you give me some advice. Thanks a lot.

**Comment by RYHSmmc** [comment]
Specifically, just like your proveided cocoref checkpoint, I want train a  model using for cityscapes, and use it for auto-drive, looking forward to your reply.

**Comment by logicwong** [comment]
1. First, You can refer to [RefCOCOg](https://one-peace-shanghai.oss-accelerate.aliyuncs.com/one_peace_datasets/refcocog.zip) to prepare your own data. Specifically, the dataset includes several tsv files and an image directory. Each tsv file contain three columns: image path, text description, and region_coord, as shown below:

```
image   text    region_coord
refcocog/image/COCO_train2014_000000533220.jpg  a bush of plant behind middle woman     285.04,23.29,424.78,146.4
refcocog/image/COCO_train2014_000000533220.jpg  Green plant behind a table visible behind a lady's head.        285.04,23.29,424.78,146.4
```

2. Refer to this [readme](https://github.com/OFA-Sys/ONE-PEACE/tree/main/one_peace) to organize your code structure and place the Cityscapes dataset in the `ONE-PEACE/one_peace/dataset/` directory. Then, follow the [instruction](https://github.com/OFA-Sys/ONE-PEACE/tree/main/one_peace#visual-grounding) to finetune the Visual Grounding model.
3. If you want to initialize the model with the provided cocoref checkpoint, remember replace the `restore_file` in this [line](https://github.com/OFA-Sys/ONE-PEACE/blob/4f18350a161df9c01f8042484f579fafb6bef75c/one_peace/run_scripts/finetune_3B.yaml#L62) with the corresponding ckpt.

**Comment by RYHSmmc** [comment]
Thanks！！
