### ISSUE TITLE
cfg.gpus_ids = [args.gpu_id] error

### ISSUE THREAD

**Issue by PL23K** [OFA-Sys/ONE-PEACE#32]
ONE-PEACE/one_peace_vision/seg/train.py
line 147 cfg.gpus_ids = [args.gpu_id]  spell error.    means:  cfg.gpu_ids = [args.gpu_id] ?  gpu_ids  not   gpus_ids

**Comment by simonJJJ** [comment]
@PL23K, thanks for pinpointing this, we fix it.
