### ISSUE TITLE
Missing of vggsound_train_new.tsv and vggsound_test_new.tsv files

### ISSUE THREAD

**Issue by AkonLau** [OFA-Sys/ONE-PEACE#34]
Thanks for sharing the helpful codebase.  

When I downloaded the `vggsound.zip` and extracted it, I found there were no such two files for training and testing. Can you provide the two scripts or other useful resources for reproducing results on VGGSound?

Looking forward to your reply.

**Comment by logicwong** [comment]
Hi, there should be two files in vggsound.zip: vggsound_train.tsv and vggsound_test.tsv. You can use these two files. The file name in the training script is incorrect, and we have just updated it.

**Comment by AkonLau** [comment]
Thank you for your reply. I have got it. Thanks again
