### ISSUE TITLE
installation fails in ubuntu 23.04

### ISSUE THREAD

**Issue by paapu88** [OFA-Sys/ONE-PEACE#38]
Dear Developers,

I fail to install you program. Here is how it goes:
- Ubuntu 23.04
- python 3.11
- standard python venv
```
python -m venv ~/venvs/onepiece
source ~/venvs/onepiece/bin/activate
git clone https://github.com/OFA-Sys/ONE-PEACE
cd ONE-PEACE
pip install -r requirements.txt
```
Getting horrible cython related errors with scikit-learn, error-
[onepiece_error.txt](https://github.com/OFA-Sys/ONE-PEACE/files/13333833/onepiece_error.txt)
file is attached.

Whats going on? My guess is that python 3.11 is too new...
Terveisin, Markus

**Comment by paapu88** [comment]
Yes, at least in my case, everything was fine (at least I was able to run 
`pip install -r requirements.txt`) without errors with Python3.9 instead of Python3.11
Terveisin, Markus

**Comment by paapu88** [comment]
Maybe you should add to the README that the code only works python <=3.10

**Comment by logicwong** [comment]
Thank you for your suggestion, we have updated Readme.
