### ISSUE TITLE
How to use this project ?

### ISSUE THREAD

**Issue by agGitHub** [OFA-Sys/ONE-PEACE#4]
Hello,

Thanks for this work ; looks really great!

May you give some details about how to use it?

Thanks a lot !

**Comment by logicwong** [comment]
@agGitHub Thanks for your interest. I will upload the pretrained checkpoint and dataset later, along with instructions for usage.

**Comment by logicwong** [comment]
@agGitHub Hi, we have uploaded [checkpoints](url) and [datasets](url). You can follow [getting_started](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace/README.md)  to test our model. We are currently working on API and demos, hoping to finish by tomorrow or the day after.

**Comment by tensorboy** [comment]
@logicwong how to combine those embeddings together to achieve multimodal inference?

**Comment by logicwong** [comment]
@tensorboy You only need to sum up these embeddings and calculate the average. 

Currently, I am working on a demo to achieve multimodal retrieval, such as audio-to-image, audio+text-to-image, audio+image-to-image, etc. Stay tuned for our later update.

**Comment by logicwong** [comment]
@agGitHub @tensorboy Hi! I have provided the [multimodal retrieval demo](https://huggingface.co/spaces/OFA-Sys/ONE-PEACE) in huggingface spaces, hope this will help you.

**Comment by tensorboy** [comment]
> @agGitHub @tensorboy Hi! I have provided the [multimodal retrieval demo](https://huggingface.co/spaces/OFA-Sys/ONE-PEACE) in huggingface spaces, hope this will help you.

Thank you for your response; it's certainly valuable and will be beneficial in my research. I'm eager to delve into the process of integrating these three modalities. Incidentally, I noticed we share the same name--quite a delightful coincidence!
