### ISSUE TITLE
Example python scripts?

### ISSUE THREAD

**Issue by paapu88** [OFA-Sys/ONE-PEACE#40]
Dear Developers,

It would be great if you could give some simple example python scripts for
1) image classification
2) sound classification
3) video action recognition

In the examples one should read in a simple input file and produce a result with a pretrained network.
Terveisin, Markus

**Comment by logicwong** [comment]
Hello, we have provided some [APIs](https://github.com/OFA-Sys/ONE-PEACE#api) in the README, can they meet your needs?

**Comment by paapu88** [comment]
No, those were not the tasks I was looking for.

**Comment by paapu88** [comment]
closed due to inactivity

**Comment by logicwong** [comment]
> No, those were not the tasks I was looking for.

Okay, I will provide sound classification API this weekend.

**Comment by logicwong** [comment]
@paapu88 Hi, we have provided the simple python scripts for audio classification [here](https://github.com/OFA-Sys/ONE-PEACE#audio-classification). If you're looking for image classification and video action recognition, please refer to this [Readme](https://github.com/OFA-Sys/ONE-PEACE/tree/main/one_peace_vision) for further guidance. We hope these resources can help you.

**Comment by paapu88** [comment]
Thanks, I can confirm your new example works perfectly (in amazon v100 with a single GPU)!
