### ISSUE TITLE
Grounding model output single modality feature

### ISSUE THREAD

**Issue by YukunZEX** [OFA-Sys/ONE-PEACE#43]
Is it possible for the grounding model input only one modality data and output the feature? I wanna use the base part of the model funtuned on grounding data, and perform the Multi-modal Embedding example

**Comment by logicwong** [comment]
I'm afraid not, the Grounding model takes both image and text modalities as input during training. If you input only one modality during inference, it seems that the model's behavior might not be normal. If you still want to do this, you could try modifying https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace/models/one_peace/one_peace_classify.py to obtain the features you want.
