### ISSUE TITLE
Vision data in datasets

### ISSUE THREAD

**Issue by kkontras** [OFA-Sys/ONE-PEACE#44]
Hi,

I would like to replicate some of the results and I started exploring the datasets. Its actually very nice that you have shared it but I was surprised to find only the audio data in some of them, for example AVQA, VGGSound and Kinetics400. Am I missing something there?

**Comment by logicwong** [comment]
In the initial version of our paper, we did not employ video data for experiments involving the VGGSound and AVQA datasets, so the initial open-source versions of these two datasets did not include video data.
In addition, the Kinetics400 dataset should contain video data. You can check it carefully.
