### ISSUE TITLE
Kernel died 

### ISSUE THREAD

**Issue by apking2000** [OFA-Sys/ONE-PEACE#46]
import torch
from one_peace.models import from_pretrained

device = "cuda" if torch.cuda.is_available() else "cpu"
model = from_pretrained("ONE-PEACE", device=device, dtype="float32")

when i try to load model my kernel died can you tell me the specification of device like memory requirements, gpu memory allocation etc?

**Comment by logicwong** [comment]
We only tested on a 40GB A100. You can try setting `dtype='float16'`.

**Comment by apking2000** [comment]
Hi can you tell me how you use the multi modality to retrieve the data ex:-
text+image to image?? It will be very helpful for me??

Thanks
Aakash

**Comment by apking2000** [comment]
Like i want to know how we combine multiple embedding to retrieve the image
data

**Comment by logicwong** [comment]
@apking2000 For guidance on implementing text+image to image retrieval, you can refer to [multi-modal-embedding](https://github.com/OFA-Sys/ONE-PEACE#multi-modal-embedding). To accomplish this, simply calculate the mean of `text_features` and `image_features`, and then employ the combined features to retrieve images.
