### ISSUE TITLE
Cuda out of memory!

### ISSUE THREAD

**Issue by aditya-inkers** [OFA-Sys/ONE-PEACE#49]
I am getting cuda out of memory error even inspite of changing the batch sizes and image sizes. Nothing is working out. Help needed!

**Comment by logicwong** [comment]
Which task are you running? Are you using fp16 training? Additionally, have apex and xformers been installed successfully?

**Comment by aditya-inkers** [comment]
I am running one_peace_vision. Here's my run command:

![Screenshot from 2024-03-04 12-38-53](https://github.com/OFA-Sys/ONE-PEACE/assets/133946296/ac333c4f-a636-4416-8b55-fcced14407ed)

I am enabled fp16_compression and also installed apex and xformer.

**Comment by logicwong** [comment]
What are the current batch size and image resolution? Can you adjust them to smaller values to see if it runs normally?
