### ISSUE TITLE
Loading local .pt file with from_pretrained failes cause of domino chain of errors.

### ISSUE THREAD

**Issue by gilkzxc** [OFA-Sys/ONE-PEACE#51]
By using the "http://one-peace-shanghai.oss-accelerate.aliyuncs.com/one-peace.pt", and from_pretrained().
I failed to load the pretrained model.
As it's prints "Killed".
So I have traced deeper to the location of the bug.
Led me to try checkpoint_utils.load_model_ensemble_and_task(), which also failed.
Eventually, I have found that an AssertionError is been raised in line 43 setup_task()
"task is not None"
![image](https://github.com/OFA-Sys/ONE-PEACE/assets/37815312/bb754acc-ddde-4818-991d-49c5b9a04f70)

**Comment by logicwong** [comment]
It might be because you haven't installed fairseq under this repo. Try:
```
pip uninstall fairseq
git clone https://github.com/OFA-Sys/ONE-PEACE
cd ONE-PEACE
pip install -r requirements.txt
```

**Comment by gilkzxc** [comment]
But I did install fairseq in the same directory.

**Comment by logicwong** [comment]
Can you share your execution command?

**Comment by gilkzxc** [comment]
![image](https://github.com/OFA-Sys/ONE-PEACE/assets/37815312/46ff290b-8b5e-429f-b0cb-f0460803edde)
That's just shows "Killed".
So I used the equivalent calls that from_pretraind() do. And then load_model.... and etc..

**Comment by logicwong** [comment]
Could it be because there's not enough memory? Try this: 
`model = from_pretrained("one-peace.pt", device=device, dtype="float16")`

**Comment by gilkzxc** [comment]
Tried with dtype="float16" and "float8", same result "Killed".

**Comment by gilkzxc** [comment]
Even reinstalled omegaconf again to be sure it's 2.0.6 as required.
![image](https://github.com/OFA-Sys/ONE-PEACE/assets/37815312/28bb2ef0-f5c4-403f-bf5f-6f6805c4d9c4)

**Comment by logicwong** [comment]
Can you switch to a machine with larger memory, and then try using `model = from_pretrained("one-peace.pt", device='cpu', dtype="float16")`? I haven't encountered this situation before.
