### ISSUE TITLE
Incorrect results when evaluate OnePiece on RefCOCO+

### ISSUE THREAD

**Issue by moonsbird29** [OFA-Sys/ONE-PEACE#59]
Hi, I evaluate OnePiece following the guidance of https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace/README.md with the weights of finetune_refcoco+.pt on dataset/refcoco+/val.tsv  on a single GPU and using fp16, but the results are: 

INFO:one_peace.evaluate:{'iou_acc': 0.29689533370514964, 'score_sum': 3194.0, 'score_cnt': 10758}

I don't know how to solve this issue, do you have any suggestions? 
Thank you!

**Comment by logicwong** [comment]
@Yunpeng-Qi Sorry for the late reply, I tested the latest code and it works fine. Can you double-check that you've updated your code and used the correct checkpoint?

`INFO:one_peace.evaluate:{'iou_acc': 0.8874326082915039, 'score_sum': 9547.0, 'score_cnt': 10758}`
