### ISSUE TITLE
Can this job be used for video classification？

### ISSUE THREAD

**Issue by Leslie-Tsui** [OFA-Sys/ONE-PEACE#6]
I want to use it for multimodal video classification tasks. What should I do？

**Comment by simonJJJ** [comment]
Hi, we released the model code in [here](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace_vision/video/mmaction_custom/models/backbones/onepeace.py). Full fine-tuning code on video classification will be released on the weekend.

If you mean the clip-style multimodal video classification tasks, just average the output embeddings of each video frame.[here](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace/models/one_peace/hub_interface.py#L180)
