### ISSUE TITLE
Excuse me, I would like to ask how to perform semantic segmentation tasks, such as training your own data set

### ISSUE THREAD

**Issue by yjq767579182** [OFA-Sys/ONE-PEACE#8]

**Comment by simonJJJ** [comment]
Hi, we use mmseg library to perform semantic segmentation. Full readme would be released [here](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace_vision/seg/README.md).

**Comment by simonJJJ** [comment]
Hi, we have released the segmentation checkpoint and scripts [here](https://github.com/OFA-Sys/ONE-PEACE/tree/main/one_peace_vision/seg).

If you want to fine-tune your own dataset, please refer [link](https://mmsegmentation.readthedocs.io/en/latest/advanced_guides/add_datasets.html) to prepare your own dataset.

**Comment by dedoogong** [comment]
can you help me how to modify your code to infer on single image? I tried to set ADE20K data following your guide but the official ADE20K data structure is different from your guide.
