### ISSUE TITLE
Hello, can you provide the pre-training script and how to use it?

### ISSUE THREAD

**Issue by Kukty** [OFA-Sys/ONE-PEACE#9]
This is a wonderful project, I would like to try to reproduce the pre-training process but don't know where to start, can you provide some help?

**Comment by logicwong** [comment]
@Kukty Sure, I will provide the pre-training script this weekend.

**Comment by logicwong** [comment]
@Kukty Hi, We have provided the pre-training script and [guidance for pretraining](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace/README.md/##Pretraining). Please check out the latest commit and have a try!

**Comment by Kukty** [comment]
> @Kukty Hi, We have provided the pre-training script and [guidance for pretraining](https://github.com/OFA-Sys/ONE-PEACE/blob/main/one_peace/README.md/##Pretraining). Please check out the latest commit and have a try!

Really appreciate it!
